### ISSUE TITLE
DSX Cloud

### ISSUE THREAD

**Issue by KCarm** [IBMDataScience/DSx-Desktop#29]
Hi, I just learned that DSX desktop and the free trial on DSX Cloud offer different functionality.  I would like to save Projects and use Flow, and I don't think the desktop version offers that.  So, I am trying to download the cloud version of DSX, but keep getting this error "Failed to obtain access token" after I enter my w3ID.  Any suggestions on how to obtain access?  Thanks.

**Comment by Debbani** [comment]
@KCarm Were you able to resolve your issue with the failed token for DSX on cloud? There was some issue with that a few days back but has been resolved now. Please let me know if you're still running into issues. Regarding DSX Desktop, we'll be supporting Projects very soon.

**Comment by KCarm** [comment]
Hi, nope, I still get the "Failed to obtain access token" error message and am unable to install the Cloud version.   Any advice?

**Comment by ucbdiaz2015** [comment]
@KCarm Projects are supported on DSX Desktop as of V1.1.7

https://datascience.ibm.com/docs/content/desktop/whatsnew.html?audience=desktop&context=analytics

**Comment by jerry1100** [comment]
Closing due to lack of activity. Reopen if needed.
