### ISSUE TITLE
Notebook does not load when opened in Windows 10.

### ISSUE THREAD

**Issue by amitakamat** [IBMDataScience/DSx-Desktop#8]
Notebook gets created successfully (create new or from existing file) but does not load when opened. 

There were two errors in spite of trying various troubleshooting options during the lab in SJSU. Please find attached the logs for both the errors and the screenshot of the issue.

OS : Windows 10 Home edition
Docker : Docker Toolbox version 1.13.0

[dsx issue.zip](https://github.com/IBMDataScience/DSx-Desktop/files/971371/dsx.issue.zip)

**Comment by nmarkey10** [comment]
@amitakamat It seems like the space in your username is breaking the Docker command.  The issue is addressed in a new image.  I will notify you when the new image is pushed.  For now, if you wan to try and run the following command, you can start the images manually. 

`(@FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd ibm-dsx') DO @%i) && docker run -d --name anaconda_with_spark  -p 49989:8888 -v //c//Users/Amita Kamat/AppData/Roaming/ibm-dsx-desktop/Notebooks/myNotebooks:/opt/notebooks na.cumulusrepo.com/homer/anaconda_with_spark:v2.1
(@FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd ibm-dsx') DO @%i) && docker run -d --name rstudio-server  -p 49988:8787 -v "//c//Users/Amita Kamat/AppData/Roaming/ibm-dsx-desktop/RStudio/myRFiles":/home/rstudio na.cumulusrepo.com/homer/rstudio-server:v2`

If you run those commands and start the app afterwards, it should manually fix your problem.  If you do this, please report back and let me know if it works or not.  Thank you!

**Comment by amitakamat** [comment]
@nmarkey10 : Hi, I tried running the two commands. They downloaded and extracted some files. But the issue still persists. Its the same error in the logs. 
I tried running the above commands again and it gave me the following messages:

time="2017-05-02T19:54:21-07:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"                                                                                           C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Conflict. The container name "/anaconda_with_spark" is already in use by container "5a322d47527f711bdf4519318260d6471cb4b028e44083508b7bcf89d11f647e". You have to remove (or rename) that container to be able to reuse that name.. 

time="2017-05-02T19:54:47-07:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"                                                                                           C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Conflict. The container name "/rstudio-server" is already in use by container "c57e865bcb55e71136481d0e6feed83dc229b33270ff9058dc0fb4be1366562d". You have to remove (or rename) that container to be able to reuse that name..

I haven't worked on docker before so I am not sure what I need to do further.

**Comment by obarrot** [comment]
+1 same problem... 
Let us know when this will be corrected

**Comment by nmarkey10** [comment]
@amitakamat @obarrot The newest version has been pushed!  There are a lot of updates and changes that went into 1.1.4 and it should solve both of your issues.  Before installing the new version, please make sure you uninstall the current one, using the app uninstaller under the settings menu within the app itself.  Thank you for your patience, please let me know if you guys run into any problems or have any questions.

**Comment by Debbani** [comment]
@amitakamat @obarrot Closing this issue, please reopen the issue if your problem still persists.
